variable "access_key" {}
variable "secret_key" {}
variable "avail_zone" {}
variable "vpc_cidr_block" {}
variable "subnet_cidr_block" {}
variable "env_prefix" {}
variable "az" {}
variable "my_public_key_location" {}
variable "instance_type" {}
variable "instance_count" {}
variable "image_name" {}
